# Generated by Django 5.2.9 on 2025-12-24 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADHDQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_sustaining_attention', models.IntegerField(help_text='0 → No attention issues, 1 → Mild difficulty, 2 → Moderate difficulty, 3 → Severe difficulty focusing', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('easily_distracted', models.IntegerField(help_text='0 → Not distracted, 1 → Mild distraction, 2 → Gets distracted often, 3 → Very easily distracted', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('forgetful_daily_tasks', models.IntegerField(help_text='0 → Never forgets, 1 → Sometimes forgets, 2 → Often forgets, 3 → Forgets very often', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('poor_organization', models.IntegerField(help_text='0 → Very organized, 1 → Slightly disorganized, 2 → Moderately poor organization, 3 → Very poor organization', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('restlessness', models.IntegerField(help_text='0 → Calm, 1 → Mild restlessness, 2 → Often restless, 3 → Very restless', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('impulsivity_score', models.IntegerField(help_text='0 → Not impulsive, 1 → Slightly impulsive, 2 → Often impulsive, 3 → Very impulsive', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('screen_time_daily', models.FloatField(help_text='Daily screen time in hours (1.0-10.0)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('phone_unlocks_per_day', models.IntegerField(help_text='Number of phone unlocks per day (20-200)', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('working_memory_score', models.IntegerField(help_text='Memory ability score (20-80)', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)])),
                ('adhd_score', models.FloatField(blank=True, null=True)),
                ('adhd_label', models.IntegerField(blank=True, choices=[(0, 'No ADHD'), (1, 'ADHD')], help_text='0 = No ADHD, 1 = ADHD', null=True)),
                ('adhd_risk_level', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhd_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepressionQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_pleasure', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('feeling_depressed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('sleep_problems', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('energy_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('appetite_changes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('self_esteem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('concentration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('psychomotor_changes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('suicidal_thoughts', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('physical_symptoms', models.TextField(blank=True)),
                ('emotional_state', models.TextField(blank=True)),
                ('life_events', models.TextField(blank=True)),
                ('depression_score', models.FloatField(blank=True, null=True)),
                ('depression_level', models.CharField(blank=True, choices=[('MINIMAL', 'Minimal Depression'), ('MILD', 'Mild Depression'), ('MODERATE', 'Moderate Depression'), ('MODERATELY_SEVERE', 'Moderately Severe Depression'), ('SEVERE', 'Severe Depression')], max_length=20, null=True)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depression_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
