# Generated by Django 5.2.9 on 2025-12-24 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_health_check', '0002_add_adhd_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhdquestionnaire',
            name='difficulty_sustaining_attention',
            field=models.IntegerField(help_text='0 → No attention issues, 1 → Mild difficulty, 2 → Moderate difficulty, 3 → Severe difficulty focusing', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='adhdquestionnaire',
            name='forgetful_daily_tasks',
            field=models.IntegerField(help_text='0 → Never forgets, 1 → Sometimes forgets, 2 → Often forgets, 3 → Forgets very often', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='adhdquestionnaire',
            name='phone_unlocks_per_day',
            field=models.IntegerField(help_text='Number of phone unlocks per day (20-200)', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='adhdquestionnaire',
            name='poor_organization',
            field=models.IntegerField(help_text='0 → Very organized, 1 → Slightly disorganized, 2 → Moderately poor organization, 3 → Very poor organization', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='adhdquestionnaire',
            name='screen_time_daily',
            field=models.FloatField(help_text='Daily screen time in hours (1.0-10.0)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='adhdquestionnaire',
            name='working_memory_score',
            field=models.IntegerField(help_text='Memory ability score (20-80)', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
